import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import ExcelJS from "exceljs";
import { saveAs } from "file-saver";
import Roboto from "../assets/fonts/Roboto-Regular.ttf";

// 🔥 FONT REGISTER
const loadFont = (doc) => {
    doc.addFileToVFS("Roboto-Regular.ttf", Roboto);
    doc.addFont("Roboto-Regular.ttf", "Roboto", "normal");
  };

// 🟢 EXCEL EXPORT
export const exportToExcel = async (data) => {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet("Communal");
  
    // 📌 HEADER
    worksheet.columns = [
      { header: "Услуга", key: "service", width: 25 },
      { header: "Дата", key: "date", width: 15 },
      { header: "Примечание", key: "desc", width: 35 },
      { header: "Сумма", key: "sum", width: 15 },
    ];
  
    // 📌 HEADER STYLE
    worksheet.getRow(1).eachCell((cell) => {
      cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "4F46E5" }, // indigo
      };
      cell.alignment = { horizontal: "center" };
    });
  
    // 📌 DATA
    data.forEach((item) => {
      worksheet.addRow({
        service: item.titleCommunal?.title || item.titleCommunal,
        date: new Date(item.dateOfPayment).toLocaleDateString("ru-RU"),
        desc: item.desc || "-",
        sum: item.sum,
      });
    });
  
    // 📌 BORDER + ZEBRA
    worksheet.eachRow((row, rowNumber) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: "thin" },
          left: { style: "thin" },
          bottom: { style: "thin" },
          right: { style: "thin" },
        };
  
        if (rowNumber % 2 === 0 && rowNumber !== 1) {
          cell.fill = {
            type: "pattern",
            pattern: "solid",
            fgColor: { argb: "F1F5F9" },
          };
        }
      });
    });
  
    // 📌 EXPORT
    const buffer = await workbook.xlsx.writeBuffer();
    saveAs(new Blob([buffer]), "communal.xlsx");
  };

// 🔴 PDF EXPORT
export const exportToPDF = (data) => {
    const doc = new jsPDF();
  
    // 🎨 HEADER BACKGROUND
    doc.setFillColor(16, 185, 129); // emerald
    doc.rect(0, 0, 210, 30, "F");
  
    // 🧾 TITLE
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(255, 255, 255);
    doc.text("COMMUNAL REPORT", 14, 18);
  
    // 📅 DATE
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Generated: ${new Date().toLocaleDateString()}`,
      140,
      18
    );
  
    // 🔄 TEXT COLOR RESET
    doc.setTextColor(0, 0, 0);
  
    // 📊 DATA
    const tableData = data.map((item) => [
      item.titleCommunal?.title || item.titleCommunal || "-",
      item.dateOfPayment
        ? new Date(item.dateOfPayment).toLocaleDateString("ru-RU")
        : "-",
      item.desc || "-",
      `${Number(item.sum || 0).toLocaleString()} UZS`,
    ]);
  
    // 📋 TABLE
    autoTable(doc, {
      startY: 40,
      head: [["Service", "Date", "Note", "Amount"]],
      body: tableData,
  
      theme: "grid",
  
      styles: {
        font: "helvetica",
        fontSize: 10,
        cellPadding: 6,
        valign: "middle",
      },
  
      headStyles: {
        fillColor: [16, 185, 129], // emerald
        textColor: 255,
        fontStyle: "bold",
        halign: "center",
      },
  
      alternateRowStyles: {
        fillColor: [240, 253, 244],
      },
  
      columnStyles: {
        0: { cellWidth: 45 },
        1: { cellWidth: 35 },
        2: { cellWidth: 70 },
        3: { cellWidth: 30, halign: "right" },
      },
    });
  
    // 💰 TOTAL
    const total = data.reduce((acc, item) => acc + Number(item.sum || 0), 0);
  
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
  
    doc.text(
      `TOTAL: ${total.toLocaleString()} UZS`,
      14,
      doc.lastAutoTable.finalY + 10
    );
  
    // 📌 FOOTER
    doc.setFontSize(9);
    doc.setTextColor(120);
  
    doc.text(
      "Generated by HomeFI System",
      14,
      285
    );
  
    // 💾 SAVE
    doc.save("communal-report.pdf");
  };